### ISSUE TITLE
Enable cache on Thumb.axd and Tansform.axd

### ISSUE THREAD

**Issue by lcssk8board** [Codvanced/framework#12]
Add the possibility to end-users choose to use cache or not when calling Thumb.axd and Tansform.axd (and the cache expiration time)

**Comment by thiagocarreno** [comment]
I started this issue in branch "".

**Comment by thiagocarreno** [comment]
Observation:

If the IIS is configured to Classic Mode is necessary configure axd in httpHandlers node, if the IIS is configured to Integrated Mode is necessary configure axd in handlers node.

Configuration of axd to Classic Mode:
<system.web>
    <httpHandlers>
      <add verb="*" path="*.thumb.axd" type="IOC.FW.Web.Handler.ThumbHandler, IOC.FW.Web" />
      <add verb="*" path="*.transform.axd" type="IOC.FW.Web.Handler.TransformHandler, IOC.FW.Web" />
    </httpHandlers>    
</system.web>

Configuration of axd to Integrated Mode:
<system.webServer>
    <handlers>
      <remove name="ThumbHandler" />
      <remove name="TransformHandler" />
      <add name="ThumbHandler" preCondition="integratedMode" verb="*" path="*.thumb.axd" type="IOC.FW.Web.Handler.ThumbHandler" />
      <add name="TransformHandler" preCondition="integratedMode" verb="*" path="*.transform.axd" type="IOC.FW.Web.Handler.TransformHandler" />
    </handlers>    
</system.webServer>
