### ISSUE TITLE
IOC.FW.Web.Helper.Pagination is useful?

### ISSUE THREAD

**Issue by lcssk8board** [Codvanced/framework#13]
Think again if the IOC.FW.Web.Helper.Pagination is useful

**Comment by thiagocarreno** [comment]
I think isn

**Comment by lucasteles** [comment]
I agree with @thiagocarreno, in general the pagination should to be in database, but can be useful in certain specific cases or in alternative types of repository. 

I think we have to maintain that option.

**Comment by lcssk8board** [comment]
Ok, I agree with you guys...
So, @thiagocarreno, please can assign for you and work on it when possible?

**Comment by thiagocarreno** [comment]
I will assigned with me.
