### ISSUE TITLE
Multiple constructors not allowed for DryIoc

### ISSUE THREAD

**Issue by lcssk8board** [Codvanced/framework#34]
DryIoc in the last version changed resolve implementations with only one constructor.
Need to fix is ASAP.

**Comment by thiagocarreno** [comment]
I stated this issue in branch "multiple-container-dryioc-adapter".

**Comment by thiagocarreno** [comment]
Finish issue with 9c210b1eee04cf1a03ee4d5f187b5a670e374ef0.
