### ISSUE TITLE
SimpleInjectorAdapter needs to be done, there is two methods not implemented

### ISSUE THREAD

**Issue by lcssk8board** [Codvanced/framework#6]
- public object Resolve(Type service, object serviceKey) are not implemented
- public TService Resolve<TService>(object serviceKey) are not implemented

**Comment by lcssk8board** [comment]
As the follow link, simple injector deliberately removed the registration/resolve services by key names... 
They prefer that we create class factory to create instances

http://simpleinjector.readthedocs.org/en/latest/howto.html#resolve-instances-by-key

So I'm closing this issue with invalid resolution state and leave a question on it...

Will we mantain this container on our list with two "throw new NotImplementedExceptions" or just remove it?

**Comment by thiagocarreno** [comment]
I think better solution is shoot "throw new NotImplementedExceptions", because this is a very nice feature of DryIoc for example, but, we can development a solution for this in simple injection and others containers that don't have this feature.

**Comment by lcssk8board** [comment]
For containers that don't have "service keys", the better approach in my opinion is pass the responsability of register/resolve multiple implementations for the end-user.

Inside the core of the framework we can use a simple "enum" to find the correct Repository implementation, it's help us to be container agnostic.

But this is other thread for another issue... so, still throwing a NotImplementedException and closing this issue.

**Comment by thiagocarreno** [comment]
For me ok.
I agree.
