### ISSUE TITLE
IOC.FW.Authentication is Necessary ?

### ISSUE THREAD

**Issue by thiagocarreno** [Codvanced/framework#62]
In assembly "IOC.FW.Authentication" we have only one class "BasicAuthenticationIdentity.cs", this class is a model and not work alone, this class was thought for work with a mvc filter or handle.

The assembly IOC.FW.Authentication is necessary ?

**Comment by thiagocarreno** [comment]
@lcssk8board What do you think about this ?

**Comment by lcssk8board** [comment]
Well, there is not a need for this assembly since it's totally coupled to MVC.
If there is no breaking changed involved, let's remove it and close this issue.

**Comment by thiagocarreno** [comment]
Ok,

I think this too. So, I will remove this class and close this issue.
