### ISSUE TITLE
Maybe we can change things in config, from configuration to conventions.

### ISSUE THREAD

**Issue by lcssk8board** [Codvanced/framework#7]
Suggestion: Transform all assemblies configures in 
		
injectionFactory
	injection
		add key="BusinessAssembly" value="IOC.Binding, IOC.Binding.SimpleInjector.BusinessModule"
		add key="DaoAssembly" value="IOC.Binding, IOC.Binding.SimpleInjector.DAOModule"
	injection
injectionFactory
  
to have some convenction type and be discovered in a folder of dependencies...
from all assemblies in a folder, load all entries of our injection interface and load modules into container.

**Comment by thiagocarreno** [comment]
The framework will undergo redesigns and it will be done after the makeover.
